from __future__ import annotations

from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "EVOLUTION_REPORT.md"
TEXT = REPORT.read_text(encoding="utf-8")


class EvolutionReportContractTests(unittest.TestCase):
    def test_report_declares_scope_provenance_and_audience(self) -> None:
        self.assertIn("**Status:** reviewed current-state synthesis", TEXT)
        self.assertIn("**Snapshot date:**", TEXT)
        self.assertIn("**Baseline before this report update:**", TEXT)
        self.assertIn("**Audience:**", TEXT)
        self.assertIn("repository-authored index and synthesis", TEXT)
        self.assertIn("It is **not** the live Bayesian", TEXT)

    def test_report_separates_evidence_classes(self) -> None:
        for evidence_class in (
            "Implemented mechanism",
            "Synthetic/test evidence",
            "Observed repository evidence",
            "Accepted / independent evidence",
        ):
            with self.subTest(evidence_class=evidence_class):
                self.assertIn(evidence_class, TEXT)

    def test_report_names_current_gates_bottleneck_and_decision(self) -> None:
        self.assertIn("Issue #151", TEXT)
        self.assertIn("Issue #57", TEXT)
        self.assertIn("Issue #86", TEXT)
        self.assertIn("## Highest-priority bottleneck", TEXT)
        self.assertIn("## Next bounded decision", TEXT)
        self.assertIn("complete one genuinely independent current-main", TEXT)

    def test_report_links_canonical_context_and_update_procedure(self) -> None:
        for target in (
            "[EVOLUTION.md](EVOLUTION.md)",
            "[ROADMAP.md](ROADMAP.md)",
            "[ITERATION_MODEL.md](ITERATION_MODEL.md)",
            "[MATHEMATICAL_FOUNDATIONS.md](MATHEMATICAL_FOUNDATIONS.md)",
            "[PROJECT_RULES.md](PROJECT_RULES.md)",
        ):
            with self.subTest(target=target):
                self.assertIn(target, TEXT)
        self.assertIn("## Update procedure", TEXT)
        self.assertIn("verify issue/PR state against current GitHub", TEXT)

    def test_authored_report_is_not_described_as_generated_runtime_state(self) -> None:
        self.assertNotIn("This file is regenerated by `scripts/evolution_score.py`", TEXT)
        self.assertNotIn("has not yet processed its first normalized GitHub event", TEXT)
        self.assertIn("exact-run `evolution-checkpoint-v2-<run_id>` artifacts", TEXT)


if __name__ == "__main__":
    unittest.main()
